port: 7890
socks-port: 7891
mixed-port: 7893
mode: global
log-level: silent
allow-lan: true
unified-delay: true
external-controller: 0.0.0.0:9090
secret : ""
bind-address: "*"
external-ui: yacd-gh-pages
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.0/8
  use-hosts: true
nameserver:
    - https://cloudflare-dns.com/dns-query
proxies:

rules:
  - MATCH,GLOBAL 
